### ISSUE TITLE
Some entries are not parsed

### ISSUE THREAD

**Issue by MaXal** [Salomon88/analyze-helper-plugin#2]
Example:
```
+ /vendor/squizlabs/php_codesniffer/src/Tokenizers/PHP.php:1047 WEAK WARNING is_array($tokens[$x]) === false 'Condition is unnecessary because it is checked by '$tokens[$x] === '('''
```
on `b2c` project.

![image](https://user-images.githubusercontent.com/266747/132334653-762c0dfb-e1c2-4695-ab99-75ffcc0d5f6c.png)

**Comment by Salomon88** [comment]
One more 
+ /engine/Library/Smarty/plugins/shared.mb_str_replace.php:27 WEAK WARNING & 'Passed reference is not used inside body' - shopware

**Comment by MaXal** [comment]
I met many of them in different projects but couldn't find any common denominator so far.

**Comment by Salomon88** [comment]
@MaXal fix in master. Please try it

**Comment by Salomon88** [comment]
Fix was verified
